import { ExamQuestion } from "../types/app.types";

export const EXAM_QUESTIONS: ExamQuestion[] = [
  {
    id: "eq-01",
    moduleId: 1,
    moduleTitle: "Introduction to Business Broking",
    question: "What is the primary role of an Authorised Business Broker in an MSME transaction?",
    options: [
      { id: "a", text: "To guarantee bank loans for buyers" },
      { id: "b", text: "To act as an intermediary facilitating valuation, confidentiality, marketing, and negotiation between buyers and sellers" },
      { id: "c", text: "To manage the daily operations of the target business" },
      { id: "d", text: "To audit statutory tax filings as a certified auditor" }
    ],
    correctOptionId: "b",
    explanation: "Business brokers act as professional intermediaries managing confidential marketing, pricing, qualification, and closing."
  },
  {
    id: "eq-02",
    moduleId: 2,
    moduleTitle: "Foundations of Business Ownership",
    question: "In an Asset Sale compared to an Equity (Share) Sale, what is the primary benefit to the buyer?",
    options: [
      { id: "a", text: "Automatic transfer of all past undisclosed tax liabilities" },
      { id: "b", text: "Ability to step up asset depreciation basis and leave legacy liabilities behind with the seller entity" },
      { id: "c", text: "No need to execute any legal contracts" },
      { id: "d", text: "100% tax exemption on all purchase consideration" }
    ],
    correctOptionId: "b",
    explanation: "In an asset sale, the buyer acquires specified assets and avoids unassumed historical legal and tax liabilities of the selling corporate entity."
  },
  {
    id: "eq-03",
    moduleId: 3,
    moduleTitle: "Ethics & Professional Standards",
    question: "A seller wants to keep a sale strictly confidential from staff, customers, and competitors. What should the broker prepare first before releasing sensitive data?",
    options: [
      { id: "a", text: "An anonymous teaser profile and a signed Non-Disclosure Agreement (NDA)" },
      { id: "b", text: "A public banner on social media" },
      { id: "c", text: "A press release in local newspapers" },
      { id: "d", text: "An unredacted audited balance sheet emailed to all contacts" }
    ],
    correctOptionId: "a",
    explanation: "Brokers use blind (anonymous) teasers to generate initial interest, and only provide detailed CIM data after receiving a signed NDA."
  },
  {
    id: "eq-04",
    moduleId: 4,
    moduleTitle: "Finding & Pitching Sellers",
    question: "Which of the following professional partners represents the most effective referral channel for sourcing motivated business sellers in India?",
    options: [
      { id: "a", text: "Chartered Accountants (CAs), Company Secretaries, and Commercial Bankers" },
      { id: "b", text: "Retail grocery shopkeepers" },
      { id: "c", text: "Tourist travel agencies" },
      { id: "d", text: "Consumer electronics distributors" }
    ],
    correctOptionId: "a",
    explanation: "Chartered Accountants, CSs, and Bankers are trusted advisors to business owners and are the first to know about retirement plans or succession needs."
  },
  {
    id: "eq-05",
    moduleId: 5,
    moduleTitle: "Understanding Buyers",
    question: "What document should a broker request to verify that a prospective buyer possesses the financial capacity to complete an acquisition?",
    options: [
      { id: "a", text: "Proof of Funds (POF) or bank comfort letter" },
      { id: "b", text: "A handwritten promissory note" },
      { id: "c", text: "Personal social media credentials" },
      { id: "d", text: "A letter from a family member" }
    ],
    correctOptionId: "a",
    explanation: "Proof of Funds (bank statements, sanctioned credit lines, or PE fund allocations) ensures the buyer is qualified and serious."
  },
  {
    id: "eq-06",
    moduleId: 6,
    moduleTitle: "Business Valuation Fundamentals",
    question: "What does SDE stand for in MSME business valuation?",
    options: [
      { id: "a", text: "Standardized Depreciation Estimate" },
      { id: "b", text: "Seller's Discretionary Earnings (net profit adjusted for promoter salary, perks, and non-recurring expenses)" },
      { id: "c", text: "Secondary Debt Equity ratio" },
      { id: "d", text: "Systematic Dividend Expense" }
    ],
    correctOptionId: "b",
    explanation: "SDE (Seller's Discretionary Earnings) reflects the true total economic benefit generated by the business for a single full-time owner-operator."
  },
  {
    id: "eq-07",
    moduleId: 7,
    moduleTitle: "Sale Mandates & Confidentiality",
    question: "A Confidential Information Memorandum (CIM) typically includes all of the following EXCEPT:",
    options: [
      { id: "a", text: "Comprehensive historical financial performance and normalized earnings" },
      { id: "b", text: "Operational overview, growth opportunities, and customer profile" },
      { id: "c", text: "Unredacted personal Aadhaar and home bank account passwords of employees" },
      { id: "d", text: "Organizational structure, plant capacity, and key assets summary" }
    ],
    correctOptionId: "c",
    explanation: "A CIM is a professional investment document; it never contains personal confidential passwords or sensitive private identity credentials."
  },
  {
    id: "eq-08",
    moduleId: 8,
    moduleTitle: "Marketing the Business",
    question: "When marketing a business confidentially on digital M&A platforms, what information must NEVER be shown publicly in the listing headline?",
    options: [
      { id: "a", text: "Exact company legal name, address, or unredacted identifiable photographs" },
      { id: "b", text: "General sector (e.g. Precision Auto Components)" },
      { id: "c", text: "Broad region (e.g. Western India)" },
      { id: "d", text: "Revenue and EBITDA range" }
    ],
    correctOptionId: "a",
    explanation: "Disclosing the company name or identifiable building photographs breaches confidentiality before an NDA is signed."
  },
  {
    id: "eq-09",
    moduleId: 9,
    moduleTitle: "Due Diligence & Structuring Deals",
    question: "What is an 'Earnout' in deal structuring?",
    options: [
      { id: "a", text: "A mechanism where a portion of the purchase price is paid contingent upon the business achieving specified future performance targets" },
      { id: "b", text: "A fine levied on the seller for retiring" },
      { id: "c", text: "A 100% upfront cash payment with no warranties" },
      { id: "d", text: "The fee paid to local regulatory authorities" }
    ],
    correctOptionId: "a",
    explanation: "Earnouts bridge the valuation gap between optimistic sellers and cautious buyers by tying future payments to post-closing revenue or EBITDA milestones."
  },
  {
    id: "eq-10",
    moduleId: 10,
    moduleTitle: "Negotiations & Closing the Deal",
    question: "What is the primary purpose of an Escrow Account in closing a business acquisition?",
    options: [
      { id: "a", text: "To hold transaction funds or indemnity reserves securely with a neutral third party until agreed conditions are met" },
      { id: "b", text: "To convert foreign currency without Reserve Bank of India notification" },
      { id: "c", text: "To avoid paying GST on broker success fees" },
      { id: "d", text: "To invest purchase funds in high-risk crypto assets" }
    ],
    correctOptionId: "a",
    explanation: "Escrow accounts safeguard funds and ensure simultaneous exchange of consideration upon fulfillment of Conditions Precedent (CPs)."
  },
  {
    id: "eq-11",
    moduleId: 11,
    moduleTitle: "90-Day ABB Career Plan",
    question: "In the 90-Day ABB Career Blueprint, what is the critical milestone targeted by Day 60?",
    options: [
      { id: "a", text: "Signing at least 2-3 exclusive seller representation mandates with CIMs prepared" },
      { id: "b", text: "Purchasing a private corporate jet" },
      { id: "c", text: "Retiring from the business broking industry" },
      { id: "d", text: "Filing for insolvency" }
    ],
    correctOptionId: "a",
    explanation: "Securing exclusive representation mandates and preparing CIMs by Day 60 creates the deal pipeline necessary for successful closing."
  },
  {
    id: "eq-12",
    moduleId: 1,
    moduleTitle: "Introduction to Business Broking",
    question: "What is the standard range of success commissions charged by professional business brokers on MSME transactions in India?",
    options: [
      { id: "a", text: "0.1% to 0.2%" },
      { id: "b", text: "3% to 8% (often structured on a Lehman or modified Lehman scale)" },
      { id: "c", text: "40% to 50%" },
      { id: "d", text: "A flat ₹5,000 regardless of deal size" }
    ],
    correctOptionId: "b",
    explanation: "Standard broker fees for transactions under 25 Cr range between 3% and 8%, with higher percentages for smaller deal sizes."
  }
];
