/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EnrolRouteImport } from './routes/enrol'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedExamRouteImport } from './routes/_authenticated/exam'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCertificateRouteImport } from './routes/_authenticated/certificate'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrolRoute = EnrolRouteImport.update({
  id: '/enrol',
  path: '/enrol',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamRoute = AuthenticatedExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificateRoute =
  AuthenticatedCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/curriculum': typeof CurriculumRoute
  '/enrol': typeof EnrolRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/verify': typeof VerifyRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam': typeof AuthenticatedExamRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/curriculum': typeof CurriculumRoute
  '/enrol': typeof EnrolRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/verify': typeof VerifyRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exam': typeof AuthenticatedExamRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/curriculum': typeof CurriculumRoute
  '/enrol': typeof EnrolRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/certificate': typeof AuthenticatedCertificateRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exam': typeof AuthenticatedExamRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/curriculum'
    | '/enrol'
    | '/forgot-password'
    | '/reset-password'
    | '/support'
    | '/verify'
    | '/assignments'
    | '/certificate'
    | '/checkout'
    | '/dashboard'
    | '/exam'
    | '/learn'
    | '/profile'
    | '/tickets'
    | '/legal/$slug'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/curriculum'
    | '/enrol'
    | '/forgot-password'
    | '/reset-password'
    | '/support'
    | '/verify'
    | '/assignments'
    | '/certificate'
    | '/checkout'
    | '/dashboard'
    | '/exam'
    | '/learn'
    | '/profile'
    | '/tickets'
    | '/legal/$slug'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/curriculum'
    | '/enrol'
    | '/forgot-password'
    | '/reset-password'
    | '/support'
    | '/verify'
    | '/_authenticated/assignments'
    | '/_authenticated/certificate'
    | '/_authenticated/checkout'
    | '/_authenticated/dashboard'
    | '/_authenticated/exam'
    | '/_authenticated/learn'
    | '/_authenticated/profile'
    | '/_authenticated/tickets'
    | '/legal/$slug'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CurriculumRoute: typeof CurriculumRoute
  EnrolRoute: typeof EnrolRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  VerifyRoute: typeof VerifyRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrol': {
      id: '/enrol'
      path: '/enrol'
      fullPath: '/enrol'
      preLoaderRoute: typeof EnrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam': {
      id: '/_authenticated/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AuthenticatedExamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificate': {
      id: '/_authenticated/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof AuthenticatedCertificateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedCertificateRoute: typeof AuthenticatedCertificateRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamRoute: typeof AuthenticatedExamRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedCertificateRoute: AuthenticatedCertificateRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamRoute: AuthenticatedExamRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CurriculumRoute: CurriculumRoute,
  EnrolRoute: EnrolRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  VerifyRoute: VerifyRoute,
  LegalSlugRoute: LegalSlugRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
